### ISSUE TITLE
Project Review Feedback

### ISSUE THREAD

**Issue by officialkrunalkumar** [pratiksontakke/past-underwear-3653#16]
1) I watched your presentation, it was great. keep up doing good work.

2) You have used gitignore to ignore unnecessary/unwanted files from being tracked. It's a good idea.

3) Your project repo should be private and access should be granted upon requested.

4) You have not documented your code. Use markdown language and document your project by adding information about your project and steps required to run.

5) You created one file with .txt extension. It should be .sql as it contains sql queries. You should not add unnecessary statements like what will be the output of what command and stuff. It should just contain the mandatory sql queries.

6) Never hard code the database or any credentials. Prevent it from being tracked by git. 

7) Write a meaningful commit messages.

8) You have maintained a good project structure.

Overall you did well. Keep it up. keep in mind while writing the code that you should never forget to follow coding standards, adding comments and a few things as mentioned above.

**Comment by pratiksontakke** [comment]
thanks for your precious feedback @officialkrunalkumar

**Comment by pratiksontakke** [comment]
thanks for your precious feedback @officialkrunalkumar
